repair grpc docker

diff --git a/.k8s/docker/Dockerfile-bridge-grpc b/.k8s/docker/Dockerfile-bridge-grpc
--- a/.k8s/docker/Dockerfile-bridge-grpc
+++ b/.k8s/docker/Dockerfile-bridge-grpc
@@ -2,7 +2,15 @@ FROM node:16
 
 WORKDIR /app
 
-COPY ./bridge-grpc .
+COPY ./bridge-grpc ./bridge-grpc/
+COPY ./bridge-ts ./bridge-ts/
+COPY ./target/idl/*.json ./target/idl/
+COPY ./target/deploy/*.json ./target/deploy/
+COPY ./package.json .
+
+RUN npm i --production
+
+WORKDIR /app/bridge-grpc
 
 RUN npm i --production
 
@@ -10,5 +18,8 @@ RUN npm i --production
 EXPOSE 8080
 # Health_check HTTP/1.1
 EXPOSE 8081
+
+# HEALTHCHECK --interval=10s --timeout=10s --start-period=5s \
+#   CMD curl --fail http://127.0.0.1:8081 || exit 1
 
 CMD [ "npm", "start" ]
